name: 'Test Phase 2: NuGet-Published Generators'

on:
  workflow_dispatch:

jobs:

  test-packaged-generators:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity: ["--unity", ""]
        merge: ["", "--merge"]
        configuration: ["", "-c Release"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: 10.x.x

      - name: Test
        run: |
          dnx -y FGenerator.Cli --prerelease -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            "test-integration/${{ github.job }}.cs" -f -o ./.z__merged_dll__

      - name: Pathfinder
        run: |
          ls -al ./.z__merged_dll__

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}${{ matrix.unity }}${{ matrix.merge }}${{ matrix.configuration }}
          path: ./.generated/**
          include-hidden-files: true
